export const SAMPLE_PARTICIPANTS = [
  { name: 'Dr. Rahim Ahmed', role: 'Moderator / Faculty', avatar_color: '#e05555' },
  { name: 'Fatima Sultana', role: 'Student - CS Department', avatar_color: '#e09255' },
  { name: 'Kamal Hossain', role: 'Student - IT Department', avatar_color: '#4fae4e' },
  { name: 'Nusrat Jahan', role: 'Student - CS Department', avatar_color: '#0088cc' },
  { name: 'Arif Khan', role: 'Student - Engineering', avatar_color: '#9c27b0' },
  { name: 'Sadia Begum', role: 'Student - Data Science', avatar_color: '#ff5722' },
  { name: 'Tanvir Islam', role: 'Student - CS Department', avatar_color: '#009688' },
  { name: 'Rifat Chowdhury', role: 'Teaching Assistant', avatar_color: '#3f51b5' },
  { name: 'Minhaz Uddin', role: 'Student - IT Department', avatar_color: '#ff9800' },
  { name: 'Anika Rahman', role: 'Student - CS Department', avatar_color: '#795548' },
  { name: 'Shakil Hasan', role: 'Student - Engineering', avatar_color: '#607d8b' },
  { name: 'Tasnim Akter', role: 'Student - Data Science', avatar_color: '#e91e63' },
  { name: 'Jubayer Ali', role: 'Student - IT Department', avatar_color: '#00bcd4' },
  { name: 'Mehreen Fatima', role: 'Student - CS Department', avatar_color: '#8bc34a' },
  { name: 'Imran Hossain', role: 'Student - Engineering', avatar_color: '#ffc107' },
  { name: 'Sumaiya Khatun', role: 'Student - CS Department', avatar_color: '#673ab7' },
  { name: 'Nazmul Haque', role: 'Student - IT Department', avatar_color: '#2196f3' },
  { name: 'Farzana Yesmin', role: 'Student - Data Science', avatar_color: '#cddc39' },
  { name: 'Rashed Mahmud', role: 'Student - CS Department', avatar_color: '#f44336' },
  { name: 'Lamia Akter', role: 'Student - CS Department', avatar_color: '#4caf50' },
];

export const SAMPLE_TOPIC = 'How can Artificial Intelligence improve modern education systems?';

export const SAMPLE_SCRIPT_STEPS = [
  { step: 1, participantIndex: 0, type: 'opening_topic', text: "Welcome everyone! Today's topic: How can Artificial Intelligence improve modern education systems? Let's explore the benefits, challenges, and future possibilities. Please share your thoughts!", replyTo: null },
  { step: 2, participantIndex: 1, type: 'question', text: "Great topic, Dr. Ahmed! I'd like to start with a question - what specific AI tools are currently being used in universities for personalized learning?", replyTo: 1 },
  { step: 3, participantIndex: 2, type: 'answer', text: "Good question, Fatima! From what I've seen, tools like ChatGPT for tutoring, Grammarly for writing, and adaptive platforms like Khan Academy use AI to personalize learning paths based on student performance.", replyTo: 2 },
  { step: 4, participantIndex: 3, type: 'agree', text: "I agree with Kamal. Adaptive learning is one of the strongest use cases. AI can identify weak areas and adjust content difficulty automatically, which is impossible for teachers to do individually for 200+ students.", replyTo: 3 },
  { step: 5, participantIndex: 4, type: 'example', text: "Here's a real example: Georgia State University used AI chatbots to answer student queries during enrollment. They reduced 'summer melt' (students who don't show up) by 22%. That's a massive improvement!", replyTo: null },
  { step: 6, participantIndex: 5, type: 'question', text: "That's impressive, Arif! But what about data privacy concerns? These AI systems collect massive amounts of student data. How do we ensure it's not misused?", replyTo: 5 },
  { step: 7, participantIndex: 6, type: 'answer', text: "Valid concern, Sadia. Most educational AI platforms comply with FERPA regulations. But I think institutions should also have their own data governance policies and regular audits.", replyTo: 6 },
  { step: 8, participantIndex: 7, type: 'counter_reply', text: "While I appreciate Tanvir's point, FERPA alone isn't enough. Many ed-tech companies sell aggregated data to third parties. We need stricter regulations specifically for AI in education.", replyTo: 7 },
  { step: 9, participantIndex: 8, type: 'disagree', text: "I partially disagree with Rifat. Over-regulation could slow down innovation. Instead, we should focus on transparency - let students know exactly what data is collected and how it's used.", replyTo: 8 },
  { step: 10, participantIndex: 9, type: 'example', text: "Here's another perspective: Finland uses AI to help teachers, not replace them. Their AI system analyzes student essays and provides feedback suggestions to teachers, who then review and personalize the feedback.", replyTo: null },
  { step: 11, participantIndex: 10, type: 'question', text: "Interesting point, Anika! Do you think AI could eventually replace teachers entirely, or will it always be a support tool?", replyTo: 10 },
  { step: 12, participantIndex: 11, type: 'answer', text: "I don't think AI will replace teachers. Teaching involves emotional intelligence, motivation, and mentoring. AI can handle repetitive tasks like grading, but the human connection is irreplaceable.", replyTo: 11 },
  { step: 13, participantIndex: 12, type: 'agree', text: "Adding to Kamal's earlier point about adaptive learning - in our IT department, we've been using AI-powered coding platforms that adjust problem difficulty based on skill level. Very effective!", replyTo: 3 },
  { step: 14, participantIndex: 13, type: 'counter_reply', text: "That's cool, Jubayer, but those platforms can also create dependency. Students might rely too much on AI hints and struggle during actual exams.", replyTo: 13 },
  { step: 15, participantIndex: 14, type: 'example', text: "In our engineering lab, we use AI-powered simulation tools that let students experiment with designs virtually before building physical prototypes. Saves time and resources.", replyTo: null },
  { step: 16, participantIndex: 15, type: 'question', text: "Imran, that sounds amazing! But aren't those tools expensive? How can smaller institutions afford AI integration?", replyTo: 15 },
  { step: 17, participantIndex: 16, type: 'answer', text: "Good question, Sumaiya. There are open-source alternatives like TensorFlow and Hugging Face. Many cloud providers also offer free tiers for educational institutions.", replyTo: 16 },
  { step: 18, participantIndex: 17, type: 'counter_reply', text: "Expanding on Minhaz's point about privacy - I believe blockchain technology combined with AI could solve many data privacy issues in education.", replyTo: 9 },
  { step: 19, participantIndex: 18, type: 'question', text: "This has been a great discussion! My final question: What's the single most important thing institutions should do RIGHT NOW to prepare for AI integration?", replyTo: null },
  { step: 20, participantIndex: 19, type: 'final_summary', text: "Great question to wrap up, Rashed! AI offers tremendous benefits in personalized learning, automated grading, and student support. Key challenges include privacy, cost, and dependency. AI should augment teachers, not replace them. Institutions should start with small pilot programs, train faculty, and develop clear data governance policies. Thank you all!", replyTo: 19 },
];
